package scenarios

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/berttrycoding/thought-harness/internal/engine"
	"github.com/berttrycoding/thought-harness/internal/trace"
)

// goldenDir holds the committed reference event streams — the standing regression snapshot of the
// canonical engine. These WERE generated by the (now-removed) Python harness as the cross-language
// port-conformance contract; after the representation-space rebuild (M2) the cognition deliberately
// changed (the fake simulation/safety/refactor specialists + the toy MemoryKB were deleted; arithmetic
// -> compute, memory -> recall, the canned fork strings -> reasoned skeptic/advocate stances), so the
// Python streams no longer describe the engine. Go is now the ONE canonical implementation (CLAUDE.md),
// so these fixtures are REGENERATED from the Go engine and the test is a Go-canonical regression gate.
//
// Regenerate after an INTENDED cognition change with:
//
//	THOUGHT_UPDATE_GOLDEN=1 go test ./internal/scenarios -run TestGoldenParity
//
// (review the diff before committing — a regen pins whatever the engine currently does). The normal
// run asserts PER LINE: tick/kind/layer/summary EXACTLY, and data as a NORMALIZED map: numeric fields
// rounded-to-3 (so an int and a whole float compare equal), order-insensitive within the map, enum
// values serialized as NAME strings, nested lists/maps normalized recursively.
//
// The fixtures live at the repo root (go/testdata/golden); this package is two directories deep
// (go/internal/scenarios), so the test resolves the path up two levels.
const goldenDir = "../../testdata/golden"

// updateGolden reports whether the run should REWRITE the golden fixtures from the live Go stream
// instead of asserting against them (THOUGHT_UPDATE_GOLDEN=1). Used only after an intended change.
func updateGolden() bool { return os.Getenv("THOUGHT_UPDATE_GOLDEN") == "1" }

// writeGolden rewrites name.jsonl from the captured Go stream, re-serialized in the same wire shape
// the JsonlSink emits (one compact JSON object per line, keys tick/kind/layer/summary/data).
func writeGolden(t *testing.T, name string, got []map[string]any) {
	t.Helper()
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	for _, m := range got {
		if err := enc.Encode(m); err != nil {
			t.Fatalf("encode golden line for %s: %v", name, err)
		}
	}
	path := filepath.Join(goldenDir, name+".jsonl")
	if err := os.WriteFile(path, b.Bytes(), 0o644); err != nil {
		t.Fatalf("write golden %s: %v", path, err)
	}
	t.Logf("%s: REGENERATED %d lines -> %s", name, len(got), path)
}

// TestGoldenParity is the standing cross-language regression gate. For every worked scenario
// (S1..S16) plus the two run modes, it runs the Go engine on seed 7 / heuristic backend and
// asserts the captured event stream reaches FULL PARITY with the committed Python reference.
func TestGoldenParity(t *testing.T) {
	for _, sc := range All() {
		sc := sc
		t.Run(sc.ID, func(t *testing.T) {
			got := runScenarioCapture(t, sc.ID)
			assertParity(t, sc.ID, got)
		})
	}

	runModes := []struct {
		name   string
		mode   string
		prompt string
	}{
		// The CLI run defaults (cmd/thought `run`): seed 7, ticks 40, these prompts.
		{"reactive", "reactive", "What's 7×8?"},
		{"continuous", "continuous", "(awake — no task)"},
	}
	for _, rm := range runModes {
		rm := rm
		t.Run(rm.name, func(t *testing.T) {
			got := runModeCapture(t, rm.mode, rm.prompt)
			assertParity(t, rm.name, got)
		})
	}
}

// (newHeuristicEngine — seed-7 TestBackend on the given mode — is shared with scenarios_test.go;
// DefaultConfig pins Seed=7, matching the CLI `--backend heuristic` path.)

// captureLines subscribes a JsonlSink-to-buffer to the engine bus so the test sees the byte-for-byte
// same wire stream a `--log FILE` run would write. It returns the buffer and the line slice after run.
func captureLines(t *testing.T, buf *bytes.Buffer) []map[string]any {
	t.Helper()
	var out []map[string]any
	sc := bufio.NewScanner(buf)
	sc.Buffer(make([]byte, 0, 1<<20), 1<<24) // big lines (scan arrays) need a large buffer
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		var m map[string]any
		if err := json.Unmarshal([]byte(line), &m); err != nil {
			t.Fatalf("parse captured line: %v\n%s", err, line)
		}
		out = append(out, m)
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("scan capture: %v", err)
	}
	return out
}

// runScenarioCapture runs scenario `id` on a heuristic seed-7 engine and returns its event stream.
func runScenarioCapture(t *testing.T, id string) []map[string]any {
	t.Helper()
	sc, ok := Get(id)
	if !ok {
		t.Fatalf("unknown scenario %s", id)
	}
	eng := newHeuristicEngine(t, sc.Mode)
	var buf bytes.Buffer
	sink := trace.NewJsonlSinkTo(&buf)
	eng.Bus().Subscribe(sink.On)
	if _, err := RunScenario(id, eng); err != nil {
		t.Fatalf("run scenario %s: %v", id, err)
	}
	emitTrailingStability(eng)
	return captureLines(t, &buf)
}

// runModeCapture replicates the CLI `run --mode <mode>` path: submit the default prompt, then run
// the 40-tick budget, capturing the stream. Mirrors cmd/thought cmdRun for the heuristic backend.
func runModeCapture(t *testing.T, mode, prompt string) []map[string]any {
	t.Helper()
	eng := newHeuristicEngine(t, mode)
	var buf bytes.Buffer
	sink := trace.NewJsonlSinkTo(&buf)
	eng.Bus().Subscribe(sink.On)
	eng.SubmitDefault(prompt)
	eng.Run(40)
	emitTrailingStability(eng)
	return captureLines(t, &buf)
}

// emitTrailingStability replays the single end-of-run regulator.stability emit that the CLI does in
// printSummary (cmd/thought, emit=true) — Python closes every run the same way in _summary, so the
// final golden line is part of the stream. Without it the Go capture is exactly one line short.
func emitTrailingStability(eng *engine.Engine) {
	eng.Regulator().Stability(eng.Mode(), true)
}

// loadGolden reads and parses the committed Python reference stream for `name`.
func loadGolden(t *testing.T, name string) []map[string]any {
	t.Helper()
	path := filepath.Join(goldenDir, name+".jsonl")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden %s: %v", path, err)
	}
	var out []map[string]any
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		var m map[string]any
		if err := json.Unmarshal([]byte(line), &m); err != nil {
			t.Fatalf("parse golden line in %s: %v\n%s", path, err, line)
		}
		out = append(out, m)
	}
	return out
}

// assertParity compares the Go stream to the golden Python stream line-by-line and fails with the
// first divergent (line, kind) pair so the failing subsystem is immediately obvious.
func assertParity(t *testing.T, name string, got []map[string]any) {
	t.Helper()
	if updateGolden() {
		writeGolden(t, name, got)
		return
	}
	want := loadGolden(t, name)
	if len(got) != len(want) {
		t.Fatalf("%s: line count mismatch: go=%d py=%d (first divergence at %s)",
			name, len(got), len(want), firstLengthDiff(want, got))
	}
	matched := 0
	for i := range want {
		if diff := lineDiff(want[i], got[i]); diff == "" {
			matched++
		} else {
			t.Errorf("%s line %d: %s", name, i+1, diff)
			if i-matched > 8 { // cap the noise once it is clearly broken
				t.Fatalf("%s: too many divergences (%d/%d matched); stopping", name, matched, len(want))
			}
		}
	}
	if matched != len(want) {
		t.Errorf("%s: %d/%d lines matched (NOT full parity)", name, matched, len(want))
	} else {
		t.Logf("%s: %d/%d lines matched (FULL PARITY)", name, matched, len(want))
	}
}

// firstLengthDiff finds the index where two streams first differ in kind, for the length-mismatch
// message (so a count gap points at the subsystem that added/dropped a line).
func firstLengthDiff(want, got []map[string]any) string {
	n := len(want)
	if len(got) < n {
		n = len(got)
	}
	for i := 0; i < n; i++ {
		if lineDiff(want[i], got[i]) != "" {
			return fmt.Sprintf("line %d (py kind=%v / go kind=%v)", i+1, want[i]["kind"], got[i]["kind"])
		}
	}
	return fmt.Sprintf("line %d (past the shorter stream's end)", n+1)
}

// lineDiff returns "" when the two event records are at parity, else a human-readable description of
// the first differing field. Scalars (tick/kind/layer/summary) compare exactly; data compares as a
// normalized map.
func lineDiff(want, got map[string]any) string {
	for _, k := range []string{"tick", "kind", "layer", "summary"} {
		if fmt.Sprint(want[k]) != fmt.Sprint(got[k]) {
			return fmt.Sprintf("%s: py=%v go=%v", k, want[k], got[k])
		}
	}
	wd, _ := want["data"].(map[string]any)
	gd, _ := got["data"].(map[string]any)
	if !equalNorm(wd, gd) {
		return "data: " + dataFieldDiff(wd, gd)
	}
	return ""
}

// dataFieldDiff reports the differing data keys (for the failure message).
func dataFieldDiff(want, got map[string]any) string {
	keys := map[string]struct{}{}
	for k := range want {
		keys[k] = struct{}{}
	}
	for k := range got {
		keys[k] = struct{}{}
	}
	ordered := make([]string, 0, len(keys))
	for k := range keys {
		ordered = append(ordered, k)
	}
	sort.Strings(ordered)
	var parts []string
	for _, k := range ordered {
		wv, wok := want[k]
		gv, gok := got[k]
		if !wok {
			parts = append(parts, fmt.Sprintf("%s: <missing in py> go=%v", k, clip(gv)))
			continue
		}
		if !gok {
			parts = append(parts, fmt.Sprintf("%s: py=%v <missing in go>", k, clip(wv)))
			continue
		}
		if !equalNormValue(wv, gv) {
			parts = append(parts, fmt.Sprintf("%s: py=%v go=%v", k, clip(wv), clip(gv)))
		}
	}
	return strings.Join(parts, "; ")
}

func clip(v any) string {
	s := fmt.Sprint(v)
	if len(s) > 120 {
		return s[:120] + "…"
	}
	return s
}

// equalNorm compares two data maps order-insensitively with numeric round-3 and recursive
// normalization. (Go map iteration is already unordered; json.Unmarshal gives map[string]any.)
func equalNorm(a, b map[string]any) bool {
	if len(a) != len(b) {
		return false
	}
	for k, av := range a {
		bv, ok := b[k]
		if !ok || !equalNormValue(av, bv) {
			return false
		}
	}
	return true
}

// equalNormValue compares two JSON values under the oracle's normalization:
//   - numbers (json.Number/float64): rounded to 3 decimals, so an int and a whole float are equal;
//   - strings/bools/nil: exact;
//   - arrays: order-SENSITIVE element-wise (the engine's lists are deterministically ordered);
//   - objects: order-insensitive via equalNorm.
func equalNormValue(a, b any) bool {
	// numbers first (both sides decode JSON numbers as float64 by default).
	if an, aok := asNumber(a); aok {
		bn, bok := asNumber(b)
		if !bok {
			return false
		}
		return round3(an) == round3(bn)
	}
	switch av := a.(type) {
	case string:
		bv, ok := b.(string)
		return ok && av == bv
	case bool:
		bv, ok := b.(bool)
		return ok && av == bv
	case nil:
		return b == nil
	case []any:
		bv, ok := b.([]any)
		if !ok || len(av) != len(bv) {
			return false
		}
		for i := range av {
			if !equalNormValue(av[i], bv[i]) {
				return false
			}
		}
		return true
	case map[string]any:
		bv, ok := b.(map[string]any)
		return ok && equalNorm(av, bv)
	default:
		return fmt.Sprint(a) == fmt.Sprint(b)
	}
}

func asNumber(v any) (float64, bool) {
	switch x := v.(type) {
	case float64:
		return x, true
	case float32:
		return float64(x), true
	case int:
		return float64(x), true
	case int64:
		return float64(x), true
	case json.Number:
		f, err := x.Float64()
		return f, err == nil
	default:
		return 0, false
	}
}

// round3 matches the per-emit-site round(x,3); -0.0 is collapsed to 0 so the sign of zero never
// produces a spurious diff (Python json renders -0.0 as -0.0 but the value is 0).
func round3(x float64) float64 {
	if math.IsInf(x, 0) || math.IsNaN(x) {
		return x
	}
	r := math.Round(x*1000) / 1000
	if r == 0 {
		return 0
	}
	return r
}
